[package]
name = "xpenses-classifier"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
encoding_rs = "0.8.32"
encoding_rs_io = "0.1"
radix_trie = "0.2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
